Inversion Mutation
DEAP/deap pull request #594
Opened 2021-10-07 19:26 UTC by jameshughes89

Closes #592 

Adds an inversion mutation. See #592. Basically, select two points and reverse the order between the points. It's handy for when adjacency is really important as it ends up being less destructive (if that's what you're looking for). 

Notes:
- It is possible that the indices are the same or adjacent. This scenario is ignored and results in an unmodified individual
- The function was tested locally, but there are no unit test provided. I am not seeing any unit tests for any other genetic operators 
- The `end_point` is **not** selected with `random.randrange(start_index, size)` as that provides a different distribution of selected indices, which is bad. 
- I originally wrote the swapping with slicing, but thought it was too ugly.

2021-10-07 19:27 UTC, jameshughes89 commented
I see that there are citations in some comments for the genetic operators. I am unaware of the original source for inversion mutation.

2021-10-17 20:44 UTC, dalonlobo requested changes
Following issues detected with this PR:

1.	Its missing mutation probability logic, which seems to be standard with other mutations i.e. :param indpb: Independent probability for each attribute to be mutated. 
2.	Function ’mutInversion’ is missing from `__all__` one line 248
3.     The while loop could potentially be replaced by list comprehension

#2
`__all__ = ['mutGaussian', 'mutPolynomialBounded', 'mutShuffleIndexes',
           'mutFlipBit', 'mutUniformInt', 'mutInversion', 'mutESLogNormal']`

#3 
`individual[start_index:end_index] = individual[start_index:end_index][::-1]`

2021-11-13 15:58 UTC, fmder commented
Could you add a test deap/deap/tests. You can create a `test_mutation.py` file

2021-11-15 14:46 UTC, jameshughes89 commented
> Could you add a unittest deap/deap/tests. You can create a `test_mutation.py` file

I see that your other tests use `unittest`. Would you prefer that being used, or would `pytest` be OK?

2021-11-16 12:51 UTC, fmder commented
Sure, I'm just old school.

2023-01-04 12:30 UTC, jameshughes89 commented
👀 so this does not get lost to the ages

2023-02-05 15:01 UTC, fmder commented
Should really an empty chromosome raise an error? I don't see much problem about receiving empty return empty.

2023-02-05 15:43 UTC, jameshughes89 commented
> Should really an empty chromosome raise an error? I don't see much problem about receiving empty return empty.

Changed, along with the test.

2023-02-05 17:30 UTC, merged